services:
  db:
    image: postgres:16
    container_name: odoo-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d odoo"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  odoo:
    image: odoo:17
    container_name: odoo-17
    depends_on:
      db:
        condition: service_healthy
    environment:
      ODOO_RC: /etc/odoo/odoo.conf
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "8069:8069" # web
      - "8072:8072" # longpolling
    volumes:
      - odoo-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
      - ./custom-addons:/mnt/extra-addons
      - ./odoo-log:/var/log/odoo # lưu log ra host
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8069/web/ | grep -q odoo || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  db-data:
  odoo-data:
